export const ActionTypes = { 
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    CITY_VALUE:'CITY_VALUE' // тестовый экшен оставил тут

}; 